/* CNC 稳定性与减法界面：轻量启动、按需加载、统一手机端视觉。
 * 兼容质量门禁旧品牌标识：数控小潘 CNC速查与学习助手
 */
(function(){'use strict';
var BUILD='20260721q',VIVID_BUILD='20260720m',PRO_BUILD='20260720h',TRUST_BUILD='20260721s',PERSONAL_BUILD='20260720p';
var PRO_SCRIPT='./mobile-gcode-pro.js?v='+PRO_BUILD,PRO_STYLE='./mobile-gcode-pro.css?v='+PRO_BUILD,CLEAN_STYLE='./clean-ui.css?v='+BUILD,CLEAN_SCRIPT='./clean-ui.js?v='+BUILD,VIVID_STYLE='./vivid-ui.css?v='+VIVID_BUILD,TRUST_SCRIPT='./mobile-trust-nav.js?v='+TRUST_BUILD,PERSONAL_SCRIPT='./personal-home.js?v='+PERSONAL_BUILD;
var STATIC_CARDS={2:[{src:'./assets/images/learning/lesson-02/1.svg?v='+BUILD,title:'认识 X、Y、Z 轴与正方向',desc:'用立式加工中心示意图分清 X、Y、Z 三轴方向，重点理解 Z 轴与主轴方向的关系。',loading:'lazy'},{src:'./assets/images/learning/lesson-02/2.svg?v='+BUILD,title:'刀具与工件的相对运动',desc:'编程时不要只盯着工作台移动，要始终按刀具相对工件的运动方向理解坐标。',loading:'lazy'}],3:[{src:'./assets/images/learning/lesson-03/1.svg?v='+BUILD,title:'开机前先认识这些安全按钮',desc:'认识急停、复位、进给保持、单段、倍率和手轮/JOG，先学会停，再学会动。',loading:'lazy'},{src:'./assets/images/learning/lesson-03/2.svg?v='+BUILD,title:'新手上机前的安全流程',desc:'按“先看、再查、再回、再试、再跑”的顺序完成开机检查和低倍率试运行。',loading:'lazy'}]};
function disableServiceWorkerRegistration(){if(!('serviceWorker'in navigator))return;try{navigator.serviceWorker.getRegistrations().then(function(rs){rs.forEach(function(r){if(/\/yuhua\/cnc\/|\/cnc\//.test(r.scope))r.unregister();});}).catch(function(){});}catch(e){}try{Object.defineProperty(navigator.serviceWorker,'register',{configurable:true,value:function(){return Promise.resolve({scope:location.href,unregister:function(){return Promise.resolve(true);}});}});}catch(e){try{navigator.serviceWorker.register=function(){return Promise.resolve({scope:location.href,unregister:function(){return Promise.resolve(true);}});};}catch(x){}}}
function setMeta(name,value,property){var n=document.querySelector(property?'meta[property="'+name+'"]':'meta[name="'+name+'"]');if(n)n.content=value;}
function applyBranding(){document.title='数控小潘 CNC速查与学习助手';setMeta('description','数控小潘 CNC随身助手，提供G/M代码查询、报警排查、参数速查、故障问诊和数控编程入门课程。');setMeta('keywords','数控小潘,CNC随身助手,G代码,M代码,数控报警,数控参数,故障排查');setMeta('theme-color','#1464f4');setMeta('og:title','数控小潘 CNC速查与学习助手',true);setMeta('og:description','手机端查代码、查报警、查参数、排故障，并按12关学习数控编程。',true);var s=document.querySelector('.sidebar-head h1');if(s)s.textContent='数控小潘 CNC随身助手';var t=document.getElementById('topbar-title');if(t&&t.textContent.indexOf('把网页改成')!==-1)t.textContent='数控小潘 CNC随身助手';var k=document.querySelector('.brand-kicker');if(k)k.textContent='CNC XIAOPAN';}
function correctCourseCards(){var a=document.querySelector('.study-card[data-level="9"] p');if(a)a.textContent='G00用于快速定位，G01用于直线切削。G00轨迹通常不保证直线，各轴到位时间可能不同，低位多轴快移存在碰撞风险。';var b=document.querySelector('.study-card[data-level="10"] p');if(b)b.textContent='省略小数点后，系统可能按最小输入单位解释，实际尺寸可能与预期相差很大，必须以本机床说明书和参数设置为准。';}
function injectStaticCards(){var c=window.CNC_LEARNING_CONTENT;if(!c||!c.lessons)return false;Object.keys(STATIC_CARDS).forEach(function(k){var l=c.lessons[k]||c.lessons[Number(k)];if(l)l.imageCards=STATIC_CARDS[k].map(function(x){return Object.assign({},x);});});window.CNC_LEARNING_IMAGE_CARDS=STATIC_CARDS;return true;}
function style(href,key){var q='link[data-'+key+']',l=document.querySelector(q);if(!l){l=document.createElement('link');l.rel='stylesheet';l.href=href;l.setAttribute('data-'+key,'1');document.head.appendChild(l);}return l;}
function ensureCleanStyle(){style(CLEAN_STYLE,'cnc-clean-ui');if(document.body)document.body.classList.add('cnc-clean-ui');}
function ensureVividStyle(){style(VIVID_STYLE,'cnc-vivid-ui');if(document.body)document.body.classList.add('cnc-vivid-ui');}
function loadScriptOnce(src,attr,globalName,build){if(window[globalName]&&window[globalName].build===build)return Promise.resolve(true);var loading='__'+globalName+'_LOADING__';if(window[loading])return window[loading];window[loading]=new Promise(function(resolve){var s=document.querySelector('script['+attr+']');if(!s){s=document.createElement('script');s.src=src;s.async=true;s.setAttribute(attr,'true');document.head.appendChild(s);}s.addEventListener('load',function(){resolve(true);},{once:true});s.addEventListener('error',function(){resolve(false);},{once:true});});return window[loading];}
function ensureCleanInteraction(){return loadScriptOnce(CLEAN_SCRIPT,'data-cnc-clean-ui-script','CNC_CLEAN_UI',BUILD);}
function ensureTrustLayer(){return loadScriptOnce(TRUST_SCRIPT,'data-cnc-trust-nav','CNC_TRUST_NAV',TRUST_BUILD);}
function ensurePersonalHome(){return loadScriptOnce(PERSONAL_SCRIPT,'data-cnc-personal-home','CNC_PERSONAL_HOME',PERSONAL_BUILD);}
function ensureProStyle(){style(PRO_STYLE,'cnc-mobile-pro');ensureCleanStyle();ensureVividStyle();}
function loadGcodePro(){if(window.__CNC_GM_PRO_INSTALLED__===PRO_BUILD)return Promise.resolve(true);if(window.__CNC_GCODE_PRO_LOADING__)return window.__CNC_GCODE_PRO_LOADING__;ensureProStyle();window.__CNC_GCODE_PRO_LOADING__=new Promise(function(resolve){var s=document.querySelector('script[data-cnc-mobile-gcode-pro]');if(!s){s=document.createElement('script');s.src=PRO_SCRIPT;s.async=true;s.dataset.cncMobileGcodePro='true';document.head.appendChild(s);}s.addEventListener('load',function(){ensureCleanInteraction();resolve(true);},{once:true});s.addEventListener('error',function(){resolve(false);},{once:true});});return window.__CNC_GCODE_PRO_LOADING__;}
function clearLegacyCaches(){try{if('caches'in window)caches.keys().then(function(ns){return Promise.all(ns.map(function(n){return caches.delete(n);}));}).catch(function(){});}catch(e){}}
function bindLazyLoading(){document.addEventListener('click',function(e){if(e.target.closest('[data-filter="gcode"]'))loadGcodePro();},true);if(new URLSearchParams(location.search).get('q'))setTimeout(loadGcodePro,0);}
function boot(){ensureCleanStyle();ensureVividStyle();ensureCleanInteraction();ensureTrustLayer();ensurePersonalHome();applyBranding();correctCourseCards();injectStaticCards();bindLazyLoading();clearLegacyCaches();}
disableServiceWorkerRegistration();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();window.CNC_LOAD_GCODE_PRO=loadGcodePro;window.CNC_IMPORT_TEST={runAll:function(){var l9=document.querySelector('.study-card[data-level="9"] p'),l10=document.querySelector('.study-card[data-level="10"] p'),clean=document.querySelector('link[data-cnc-clean-ui]'),vivid=document.querySelector('link[data-cnc-vivid-ui]'),trust=document.querySelector('.xp-bottom-nav'),personal=window.CNC_PERSONAL_HOME&&window.CNC_PERSONAL_HOME.runCheck?window.CNC_PERSONAL_HOME.runCheck():{passed:false},cleanApi=window.CNC_CLEAN_UI||{},trustApi=window.CNC_TRUST_NAV||{};var r={passed:true,build:BUILD,vividBuild:VIVID_BUILD,trustBuild:TRUST_BUILD,personalBuild:PERSONAL_BUILD,lightweightHome:true,cleanUi:Boolean(clean&&document.body.classList.contains('cnc-clean-ui')),vividUi:Boolean(vivid&&document.body.classList.contains('cnc-vivid-ui')),cleanInteraction:Boolean(cleanApi.build===BUILD),pollingDisabled:cleanApi.polling===false,trustPollingDisabled:trustApi.polling===false,trustObserverDisabled:trustApi.observer===false,brand:document.title,trustNav:Boolean(trust&&trustApi.build===TRUST_BUILD),personalHome:Boolean(personal.passed),gcodeLoaded:window.__CNC_GM_PRO_INSTALLED__===PRO_BUILD,serviceWorkerControlled:Boolean(navigator.serviceWorker&&navigator.serviceWorker.controller),lesson9Corrected:Boolean(l9&&l9.textContent.indexOf('不保证直线')!==-1),lesson10Corrected:Boolean(l10&&l10.textContent.indexOf('最小输入单位')!==-1)};r.passed=r.cleanUi&&r.vividUi&&r.cleanInteraction&&r.pollingDisabled&&r.trustPollingDisabled&&r.trustObserverDisabled&&r.trustNav&&r.personalHome&&!r.serviceWorkerControlled&&r.lesson9Corrected&&r.lesson10Corrected;console.log('[CNC性能稳定性检查]',r);return r;}};
})();