/* 数控小潘：个性化首页、学习进度与工业卡片学习页。 */
(function(){
'use strict';
var BUILD = '20260722b';
var VISITED_KEY='cnc_study_visited_v1',DONE_KEY='cnc_study_completed_v1',CURRENT_KEY='cnc_study_current_v1',FAVORITES_KEY='cnc_app_favorites_v2',RECENTS_KEY='cnc_app_recents_v2',mounted=false;
function read(k,f){try{var v=JSON.parse(localStorage.getItem(k));return v==null?f:v;}catch(e){return f;}}
function write(k,v){try{localStorage.setItem(k,JSON.stringify(v));}catch(e){}}
function nums(a){return Array.from(new Set((Array.isArray(a)?a:[]).map(Number).filter(function(n){return n>=1&&n<=12;}))).sort(function(a,b){return a-b;});}
function esc(v){return String(v||'').replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function cards(){return Array.from(document.querySelectorAll('#view-study .study-card[data-level]'));}
function info(level){var c=document.querySelector('#view-study .study-card[data-level="'+level+'"]');return{level:Number(level)||1,title:c&&c.querySelector('h4')?c.querySelector('h4').textContent.trim():'第 '+level+' 关',desc:c&&c.querySelector('p')?c.querySelector('p').textContent.trim():'继续完成数控入门学习'};}
function state(){var visited=nums(read(VISITED_KEY,[])),done=nums(read(DONE_KEY,[])),current=read(CURRENT_KEY,null);if(!current||!current.level){var next=done.length<12?Array.from({length:12},function(_,i){return i+1;}).find(function(n){return done.indexOf(n)===-1;})||1:12;current=info(next);}return{visited:visited,done:done,current:current,favorites:read(FAVORITES_KEY,[]),recents:read(RECENTS_KEY,[])};}
function ensureAssets(){if(!document.querySelector('link[data-cnc-industrial-learning]')){var l=document.createElement('link');l.rel='stylesheet';l.href='./industrial-learning.css?v=20260722c';l.dataset.cncIndustrialLearning='1';document.head.appendChild(l);}if(document.body)document.body.classList.add('cnc-industrial-learning');if(!document.getElementById('xp-personal-home-style')){var s=document.createElement('style');s.id='xp-personal-home-style';s.textContent='.xp-personal-home{margin:18px 0 0;display:grid;gap:12px}.xp-personal-hero,.xp-continue-card,.xp-stat-card{border:1px solid #d8d3c8;border-radius:14px;background:#fffdf9;color:#292c2f;box-shadow:0 6px 16px rgba(48,44,36,.07)}.xp-personal-hero{display:grid;grid-template-columns:minmax(0,1.5fr) minmax(230px,.7fr);gap:14px;padding:18px}.xp-personal-kicker{margin:0 0 5px;color:#667b8d;font-size:12px;font-weight:900}.xp-personal-hero h2{margin:0;font-size:24px;font-weight:950}.xp-personal-hero p{color:#687078;line-height:1.6}.xp-progress-box{padding:14px;border:1px solid #d8d3c8;border-radius:12px;background:#f2efe8}.xp-progress-number{display:flex;justify-content:space-between;align-items:flex-end}.xp-progress-number strong{font-size:30px;font-weight:950}.xp-progress-track{height:9px;margin-top:12px;background:#dfdacf;border-radius:8px;overflow:hidden}.xp-progress-fill{height:100%;background:#3f6179}.xp-personal-grid{display:grid;grid-template-columns:minmax(0,1.45fr) repeat(3,minmax(110px,.55fr));gap:10px}.xp-continue-card,.xp-stat-card{padding:15px}.xp-continue-card{display:flex;justify-content:space-between;gap:14px}.xp-continue-card small,.xp-stat-card small{color:#687078;font-size:12px;font-weight:800}.xp-continue-card strong,.xp-stat-card strong{display:block;margin-top:5px;font-size:19px;font-weight:950}.xp-continue-btn,.xp-complete-btn{min-height:44px;border:1px solid #29485f;border-radius:10px;padding:10px 14px;background:#3f6179;color:#fff;font-weight:950}.xp-complete-bar{display:flex;align-items:center;justify-content:space-between;gap:10px;margin:14px 0;padding:12px;border:1px solid #d8d3c8;border-radius:12px;background:#f2efe8}.xp-complete-btn.done{background:#dce9e3;color:#2f6d55}#view-study .study-card{position:relative}#view-study .study-card.xp-completed:after{content:"已完成";position:absolute;right:12px;bottom:12px;padding:5px 9px;border-radius:7px;background:#3d8268;color:#fff;font-size:11px;font-weight:950}@media(max-width:760px){.xp-personal-hero,.xp-personal-grid{grid-template-columns:1fr}.xp-continue-card{flex-direction:column}.xp-continue-btn{width:100%;min-height:48px}}';document.head.appendChild(s);}}
function keepPanelAfterTools(panel, launch){if(panel&&launch&&launch.nextElementSibling!==panel){launch.insertAdjacentElement('afterend', panel);}}
function followsTools(){var panel=document.getElementById('xp-personal-home'),launch=document.querySelector('#view-dashboard .launchpad-grid');return Boolean(panel&&launch&&launch.nextElementSibling===panel);}
function mark(st){cards().forEach(function(c){var n=Number(c.dataset.level);c.classList.toggle('xp-visited',st.visited.indexOf(n)!==-1);c.classList.toggle('xp-completed',st.done.indexOf(n)!==-1);});}
function render(){var d=document.getElementById('view-dashboard'),launch=d&&d.querySelector('.launchpad-grid');if(!d||!launch)return false;var st=state(),panel=document.getElementById('xp-personal-home');if(!panel){panel=document.createElement('section');panel.id='xp-personal-home';panel.className='xp-personal-home';}keepPanelAfterTools(panel,launch);var current=info(st.current.level||1),percent=Math.round(st.done.length/12*100);panel.innerHTML='<div class="xp-personal-hero"><div><p class="xp-personal-kicker">学习进度</p><h2>'+(st.done.length?'接着学，不用从头再找':'从第 1 关开始，稳稳入门')+'</h2><p>功能查询在上面，学习记录放在这里；不登录也能继续。</p></div><div class="xp-progress-box"><div class="xp-progress-number"><strong>'+percent+'%</strong><span>已完成 '+st.done.length+' / 12 关</span></div><div class="xp-progress-track"><div class="xp-progress-fill" style="width:'+percent+'%"></div></div></div></div><div class="xp-personal-grid"><article class="xp-continue-card"><div><small>继续学习 · 第 '+current.level+' 关</small><strong>'+esc(current.title)+'</strong><p>'+esc(current.desc)+'</p></div><button class="xp-continue-btn" type="button" data-xp-continue="'+current.level+'">继续学习</button></article><article class="xp-stat-card"><small>已看关卡</small><strong>'+st.visited.length+'</strong></article><article class="xp-stat-card"><small>我的收藏</small><strong>'+(Array.isArray(st.favorites)?st.favorites.length:0)+'</strong></article><article class="xp-stat-card"><small>最近查看</small><strong>'+(Array.isArray(st.recents)?st.recents.length:0)+'</strong></article></div>';mark(st);return true;}
function openLesson(level){var c=document.querySelector('#view-study .study-card[data-level="'+level+'"]');if(!c)return;var st=state();st.visited=nums(st.visited.concat([level]));write(VISITED_KEY,st.visited);write(CURRENT_KEY,info(level));if(typeof window.navigate==='function')window.navigate('study');else{var n=document.querySelector('[data-route="study"]');if(n)n.click();}setTimeout(function(){c.click();c.scrollIntoView({behavior:'smooth',block:'start'});render();},80);}
function completeBar(){var content=document.getElementById('study-detail-content'),detail=content&&content.querySelector('.lesson-detail-v2[data-level]');if(!detail)return;var level=Number(detail.dataset.level),bar=detail.querySelector('.xp-complete-bar');if(!bar){bar=document.createElement('div');bar.className='xp-complete-bar';var target=detail.querySelector('.lesson-pass-box')||detail.firstElementChild;if(target)target.insertAdjacentElement('afterend',bar);else detail.prepend(bar);}var done=state().done.indexOf(level)!==-1;bar.innerHTML='<strong>'+(done?'这一关已完成，可以继续下一关':'学完并练习后，记得标记完成')+'</strong><button type="button" class="xp-complete-btn'+(done?' done':'')+'" data-xp-complete="'+level+'">'+(done?'✓ 已完成':'标记完成')+'</button>';}
function toggle(level){var st=state(),exists=st.done.indexOf(level)!==-1;st.done=exists?st.done.filter(function(n){return n!==level;}):nums(st.done.concat([level]));st.visited=nums(st.visited.concat([level]));write(DONE_KEY,st.done);write(VISITED_KEY,st.visited);if(!exists){var next=Array.from({length:12},function(_,i){return i+1;}).find(function(n){return st.done.indexOf(n)===-1;});if(next)write(CURRENT_KEY,info(next));}render();completeBar();mark(state());}
function bind(){if(mounted)return;mounted=true;document.addEventListener('click',function(e){var cont=e.target.closest&&e.target.closest('[data-xp-continue]');if(cont){openLesson(Number(cont.dataset.xpContinue));return;}var done=e.target.closest&&e.target.closest('[data-xp-complete]');if(done){toggle(Number(done.dataset.xpComplete));return;}var c=e.target.closest&&e.target.closest('#view-study .study-card[data-level]');if(c){var level=Number(c.dataset.level),st=state();st.visited=nums(st.visited.concat([level]));write(VISITED_KEY,st.visited);write(CURRENT_KEY,info(level));setTimeout(function(){render();completeBar();},80);}if(e.target.closest&&e.target.closest('#favorite-toggle'))setTimeout(render,60);},true);window.addEventListener('storage',render);}
function boot(){ensureAssets();bind();render();completeBar();setTimeout(function(){ensureAssets();render();mark(state());},900);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
window.CNC_PERSONAL_HOME={build:BUILD,render:render,getState:state,runCheck:function(){var panel=document.getElementById('xp-personal-home'),link=document.querySelector('link[data-cnc-industrial-learning]'),list=cards(),after=followsTools();return{passed:Boolean(panel&&document.querySelector('[data-xp-continue]')&&link&&document.body.classList.contains('cnc-industrial-learning')&&list.length===12&&after),build:BUILD,panel:Boolean(panel),learningStyle:Boolean(link),studyCards:list.length,followsTools:after,state:state()};}};
})();
