/* 数控小潘 CNC随身助手：报警、参数、故障独立查询与低开销初始化。 */
(function(){
  'use strict';
  var BUILD='20260721r';
  var RETRY_DELAYS=[0,40,100,220,480,900,1600];
  var retryIndex=0,retryTimer=null,originalFilter=null,originalNavigate=null,originalRender=null;
  var META={
    alarm:{label:'报警排查',kicker:'报警排查',title:'输入报警号，按顺序排查',eyebrow:'ALARM CHECK',workspaceTitle:'报警排查',placeholder:'输入报警号，例如 SV0401、PS0001、OT0500'},
    parameter:{label:'参数速查',kicker:'参数速查',title:'查参数作用、风险和修改前检查',eyebrow:'PARAMETER',workspaceTitle:'参数速查',placeholder:'输入参数号或名称，例如 1815、回零参数、主轴参数'},
    fault:{label:'故障问诊',kicker:'故障问诊',title:'按故障现象查原因和检查顺序',eyebrow:'FAULT DIAGNOSIS',workspaceTitle:'故障问诊',placeholder:'描述现象，例如 回零失败、换刀异常、尺寸不稳、主轴异响'}
  };
  function norm(v){if(typeof normalizeText==='function')return normalizeText(v||'');return String(v||'').toLowerCase().replace(/\s+/g,' ').trim();}
  function hay(e){if(typeof getEntryText==='function')return norm(getEntryText(e));return norm([e&&e.id,e&&e.category,e&&e.title,e&&e.code,e&&e.summary,e&&e.usage,e&&e.warning,e&&e.source,e&&Array.isArray(e.tags)?e.tags.join(' '):''].filter(Boolean).join(' '));}
  function parts(e){return{category:norm(e&&e.category),title:norm(e&&e.title),code:norm(e&&e.code).replace(/[\s_-]+/g,''),hay:hay(e)};}
  function alarmCode(code,text){return /^(sv|sp|ps|ot|ex|sr|ds|alm|alarm)\d{3,6}$/i.test(code)||/\b(sv|sp|ps|ot|ex|sr|ds|alm|alarm)\s*[-_]?\s*\d{3,6}\b/i.test(text);}
  function isAlarmEntry(e){var p=parts(e);return alarmCode(p.code,p.hay)||p.category.indexOf('报警')!==-1||p.title.indexOf('报警')!==-1||/报警号|伺服报警|主轴报警|过行程报警|系统报警|报警代码/.test(p.hay);}
  function isParameterEntry(e){var p=parts(e),explicit=p.category.indexOf('参数')!==-1||p.title.indexOf('参数')!==-1||/参数号|系统参数|机床参数|伺服参数|主轴参数|坐标参数|刀补参数|parameter/.test(p.hay),numeric=/^\d{3,6}$/.test(p.code)&&/参数|设定|设置|轴|伺服|主轴|坐标|回零/.test(p.hay),alarm=alarmCode(p.code,p.hay)||p.category.indexOf('报警')!==-1||p.title.indexOf('报警')!==-1;return(explicit||numeric)&&!alarm;}
  function isFaultEntry(e){var p=parts(e),signal=p.category.indexOf('故障')!==-1||p.category.indexOf('维修')!==-1||p.category.indexOf('诊断')!==-1||/故障|维修|异常|失效|失败|无法|不能|不动|异响|振动|过热|尺寸不稳|回零失败|换刀异常|卡刀|断刀|刀纹|锥度|单网纹|排查/.test(p.title+' '+p.hay),alarm=alarmCode(p.code,p.hay)||p.category.indexOf('报警')!==-1||p.title.indexOf('报警')!==-1;return signal&&!alarm;}
  function classifyEntry(e){if(isAlarmEntry(e))return'alarm';if(isParameterEntry(e))return'parameter';if(isFaultEntry(e))return'fault';return'other';}
  function patchFilters(){if(window.__CNC_QUERY_FILTER_PATCHED__)return true;try{if(typeof filterKeyMatches!=='function'||typeof FILTER_META==='undefined')return false;originalFilter=filterKeyMatches;FILTER_META.alarm={label:META.alarm.label};FILTER_META.parameter={label:META.parameter.label};FILTER_META.fault={label:META.fault.label};delete FILTER_META.params;filterKeyMatches=function(entry,key){if(key==='alarm')return isAlarmEntry(entry);if(key==='parameter')return isParameterEntry(entry);if(key==='fault')return isFaultEntry(entry);return originalFilter(entry,key);};window.__CNC_QUERY_FILTER_PATCHED__=true;return true;}catch(e){return false;}}
  function setCard(card,mode,icon,title,desc,badge){if(!card)return;card.dataset.route='workspace';card.dataset.filter=mode;card.dataset.queryMode=mode;var i=card.querySelector('.launchpad-card-icon'),h=card.querySelector('h3'),p=card.querySelector('p'),b=card.querySelector('.launchpad-badge');if(i)i.textContent=icon;if(h)h.textContent=title;if(p)p.textContent=desc;if(b)b.textContent=badge;}
  function bindRoute(button){if(!button||button.dataset.cncQueryRouteBound==='true')return;button.dataset.cncQueryRouteBound='true';button.addEventListener('click',function(){if(typeof navigate==='function')navigate('workspace',{filter:button.dataset.filter});});}
  function updateCards(){var cards=Array.from(document.querySelectorAll('.launchpad-card')),alarm=cards.find(function(c){var h=c.querySelector('h3');return h&&h.textContent.trim()==='报警排查';}),parameter=cards.find(function(c){var h=c.querySelector('h3');return h&&h.textContent.trim()==='参数速查';});setCard(alarm,'alarm','🚨','报警排查','输入报警号，查看原因和安全排查顺序','→ 查报警');setCard(parameter,'parameter','⚙','参数速查','查参数作用、适用范围和修改风险','→ 查参数');var fault=document.querySelector('.launchpad-card[data-filter="fault"]');if(!fault&&parameter){fault=document.createElement('article');fault.className='launchpad-card';fault.innerHTML='<div class="launchpad-card-icon">🩺</div><div><h3>故障问诊</h3><p>按异常现象查原因、检查顺序和处理边界</p><span class="launchpad-badge">→ 查故障</span></div>';parameter.insertAdjacentElement('afterend',fault);setCard(fault,'fault','🩺','故障问诊','按异常现象查原因、检查顺序和处理边界','→ 查故障');bindRoute(fault);}}
  function updateSidebar(){var panel=document.querySelector('[data-tree-panel="workspace"]');if(!panel)return;var legacy=panel.querySelector('.tree-item[data-filter="params"]'),alarm=panel.querySelector('.tree-item[data-filter="alarm"]');if(!alarm&&legacy){alarm=legacy;alarm.dataset.filter='alarm';alarm.textContent='报警排查';}if(!alarm)return;var parameter=panel.querySelector('.tree-item[data-filter="parameter"]');if(!parameter){parameter=alarm.cloneNode(true);parameter.dataset.filter='parameter';parameter.textContent='参数速查';parameter.removeAttribute('data-cnc-query-route-bound');alarm.insertAdjacentElement('afterend',parameter);bindRoute(parameter);}var fault=panel.querySelector('.tree-item[data-filter="fault"]');if(!fault){fault=alarm.cloneNode(true);fault.dataset.filter='fault';fault.textContent='故障问诊';fault.removeAttribute('data-cnc-query-route-bound');parameter.insertAdjacentElement('afterend',fault);bindRoute(fault);}}
  function applyMeta(){if(typeof state==='undefined')return;var m=META[state.activeFilter];if(!m){if(document.body)document.body.removeAttribute('data-cnc-query-mode');return;}document.body.setAttribute('data-cnc-query-mode',state.activeFilter);var k=document.getElementById('topbar-kicker'),t=document.getElementById('topbar-title'),e=document.getElementById('workspace-eyebrow'),w=document.getElementById('workspace-title'),i=document.getElementById('search-input');if(k){k.textContent=m.kicker;k.style.display='';}if(t)t.textContent=m.title;if(e)e.textContent=m.eyebrow;if(w)w.textContent=m.workspaceTitle;if(i)i.placeholder=m.placeholder;}
  function patchNavigation(){if(!window.__CNC_QUERY_NAV_PATCHED__){try{if(typeof navigate!=='function')return false;originalNavigate=navigate;navigate=function(){var r=originalNavigate.apply(this,arguments);queueMicrotask(applyMeta);return r;};if(window.app)window.app.navigate=navigate;window.__CNC_QUERY_NAV_PATCHED__=true;}catch(e){return false;}}if(!window.__CNC_QUERY_RENDER_PATCHED__){try{if(typeof renderWorkspace!=='function')return false;originalRender=renderWorkspace;renderWorkspace=function(){var r=originalRender.apply(this,arguments);applyMeta();return r;};window.__CNC_QUERY_RENDER_PATCHED__=true;}catch(e){return false;}}return true;}
  function getCounts(){if(typeof state==='undefined'||!Array.isArray(state.entries))return{alarm:0,parameter:0,fault:0};return state.entries.reduce(function(c,e){var type=classifyEntry(e);if(c[type]!==undefined)c[type]++;return c;},{alarm:0,parameter:0,fault:0});}
  function install(){if(!patchFilters())return false;updateCards();updateSidebar();if(!patchNavigation())return false;if(typeof renderPresetChips==='function')renderPresetChips();applyMeta();window.CNC_QUERY_MODES={build:BUILD,polling:false,maxReadinessAttempts:RETRY_DELAYS.length,classifyEntry:classifyEntry,getCounts:getCounts,applyModeMeta:applyMeta,refresh:function(){updateCards();updateSidebar();applyMeta();}};window.__CNC_QUERY_READY_AT__=Math.round(performance.now());return true;}
  function check(){retryTimer=null;if(install())return;schedule();}
  function schedule(){if(retryTimer!==null||retryIndex>=RETRY_DELAYS.length)return;retryTimer=setTimeout(check,RETRY_DELAYS[retryIndex++]);}
  schedule();document.addEventListener('DOMContentLoaded',schedule,{once:true});window.addEventListener('load',schedule,{once:true});
})();
