/* CNC PWA：版本化缓存、离线回退与安全更新。 */
const BUILD='20260726-pwa1';
const STATIC_CACHE=`cnc-static-${BUILD}`;
const RUNTIME_CACHE=`cnc-runtime-${BUILD}`;
const CORE=['./','./index.html','./offline.html','./manifest.webmanifest','./styles.css','./styles-enhanced.css','./app.js','./training-camp.html','./practice.html','./profile.html','./simulator-hub.html'];
self.addEventListener('install',event=>{event.waitUntil(caches.open(STATIC_CACHE).then(cache=>cache.addAll(CORE)).then(()=>self.skipWaiting()));});
self.addEventListener('activate',event=>{event.waitUntil((async()=>{const names=await caches.keys();await Promise.all(names.filter(name=>name.startsWith('cnc-')&&!name.endsWith(BUILD)).map(name=>caches.delete(name)));await self.clients.claim();})());});
self.addEventListener('message',event=>{if(event.data&&event.data.type==='SKIP_WAITING')self.skipWaiting();if(event.data&&event.data.type==='GET_BUILD')event.source&&event.source.postMessage({type:'CNC_SW_BUILD',build:BUILD});});
self.addEventListener('fetch',event=>{const req=event.request;if(req.method!=='GET')return;const url=new URL(req.url);if(url.origin!==self.location.origin)return;if(req.mode==='navigate'){event.respondWith((async()=>{try{const fresh=await fetch(req);const cache=await caches.open(RUNTIME_CACHE);cache.put(req,fresh.clone());return fresh;}catch{const cached=await caches.match(req)||await caches.match('./index.html');return cached||caches.match('./offline.html');}})());return;}event.respondWith((async()=>{const cached=await caches.match(req);const refresh=fetch(req).then(async response=>{if(response&&response.ok){const cache=await caches.open(RUNTIME_CACHE);cache.put(req,response.clone());}return response;}).catch(()=>null);return cached||await refresh||new Response('',{status:504,statusText:'Offline'});})());});
