/* CNC 新手训练平台：成长档案、课程成绩、薄弱项与下一步推荐。 */
(function(){
'use strict';
var BUILD='20260723f',PRACTICE_KEY='cnc_training_practice_v1',PROFILE_KEY='cnc_training_profile_v1',DONE_KEY='cnc_study_completed_v1',CURRENT_KEY='cnc_study_current_v1';
function read(key,fallback){try{var value=JSON.parse(localStorage.getItem(key));return value==null?fallback:value;}catch(error){return fallback;}}
function esc(value){return String(value==null?'':value).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function lessonTitle(level){var card=document.querySelector('#view-study .study-card[data-level="'+level+'"]');var title=card&&card.querySelector('h4');return title?title.textContent.trim():'第 '+level+' 关';}
function practice(){var value=read(PRACTICE_KEY,null);return value&&value.version===1?value:{version:1,attempts:{},wrong:[],correct:[],lessonScores:{}};}
function profile(){var value=read(PROFILE_KEY,null);return value&&value.version===1?value:{version:1,xp:0,badges:[],completed:[]};}
function snapshot(){var p=practice(),user=profile(),done=(read(DONE_KEY,[])||[]).map(Number),scores=p.lessonScores||{},lessons=Array.from({length:12},function(_,i){var level=i+1,score=Number(scores[level]||0),completed=done.indexOf(level)!==-1;return{level:level,title:lessonTitle(level),score:score,completed:completed,status:completed?'已通过':score>=80?'待记录通关':score>0?'继续练习':'尚未开始'};}),weak=lessons.filter(function(item){return item.score>0&&item.score<80;}),next=lessons.find(function(item){return !item.completed;})||lessons[11],wrong=Array.isArray(p.wrong)?p.wrong:[];return{xp:Number(user.xp)||0,badges:Array.isArray(user.badges)?user.badges:[],completed:done.length,wrong:wrong.length,lessons:lessons,weak:weak,next:next,current:read(CURRENT_KEY,null)};}
function ensureAssets(){if(!document.querySelector('link[data-cnc-training-profile]')){var link=document.createElement('link');link.rel='stylesheet';link.href='./training-profile.css?v='+BUILD;link.dataset.cncTrainingProfile='1';document.head.appendChild(link);}if(document.body)document.body.dataset.cncTrainingProfileBuild=BUILD;}
function scoreCard(item){return '<article class="xp-profile-score '+(item.completed?'is-complete':item.score>0?'is-active':'is-empty')+'" role="listitem"><div class="xp-profile-score-head"><span>第 '+item.level+' 关</span><strong>'+item.score+'<small>/100</small></strong></div><h4>'+esc(item.title)+'</h4><div class="xp-profile-score-track" aria-label="第 '+item.level+' 关成绩 '+item.score+' 分"><i style="width:'+Math.max(0,Math.min(100,item.score))+'%"></i></div><p>'+esc(item.status)+'</p></article>';}
function render(){ensureAssets();var view=document.getElementById('view-favorites');if(!view)return false;var grid=view.querySelector('.favorites-grid')||view.querySelector('.section-panel')||view;var panel=document.getElementById('xp-training-profile');if(!panel){panel=document.createElement('section');panel.id='xp-training-profile';panel.className='xp-training-profile';grid.insertAdjacentElement('beforebegin',panel);}var data=snapshot(),weakText=data.weak.length?data.weak.map(function(item){return '第 '+item.level+' 关 '+item.score+' 分';}).join('、'):'暂无低于80分的已练课程';panel.innerHTML='<div class="xp-profile-head"><div><p class="xp-profile-kicker">我的成长档案 · '+BUILD+'</p><h3>CNC 新手成长记录</h3><p>集中查看课程成绩、薄弱项、错题和下一步训练建议。</p></div><div class="xp-profile-xp"><strong>'+data.xp+'</strong><span>XP</span></div></div><div class="xp-profile-stats"><span><strong>'+data.completed+'/12</strong>已通过课程</span><span><strong>'+data.wrong+'</strong>当前错题</span><span><strong>'+data.badges.length+'</strong>训练徽章</span></div><div class="xp-profile-recommend"><div><small>推荐下一步</small><strong>第 '+data.next.level+' 关 · '+esc(data.next.title)+'</strong><p>'+esc(data.next.status)+'，建议先完成课程讲解，再把本关练习做到80分以上。</p></div><button type="button" data-profile-continue="'+data.next.level+'">继续训练</button></div><div class="xp-profile-weak"><strong>薄弱项</strong><p>'+esc(weakText)+'</p>'+(data.wrong?'<button type="button" data-profile-wrong>重做错题</button>':'')+'</div><div class="xp-profile-score-list" role="list" aria-label="12关课程成绩">'+data.lessons.map(scoreCard).join('')+'</div>';view.dataset.trainingProfile='ready';return true;}
function openLesson(level){var nav=document.querySelector('[data-route="study"],[data-xp-route="study"]');if(nav)nav.click();window.setTimeout(function(){var card=document.querySelector('#view-study .study-card[data-level="'+level+'"]');if(card){card.click();card.scrollIntoView({behavior:'smooth',block:'start'});}},120);}
function bind(){if(window.__CNC_TRAINING_PROFILE_BOUND__)return;window.__CNC_TRAINING_PROFILE_BOUND__=true;document.addEventListener('click',function(event){var route=event.target.closest&&event.target.closest('[data-route="favorites"],[data-xp-route="favorites"]');if(route)window.setTimeout(render,80);var cont=event.target.closest&&event.target.closest('[data-profile-continue]');if(cont){openLesson(Number(cont.dataset.profileContinue));return;}if(event.target.closest&&event.target.closest('[data-profile-wrong]')){var study=document.querySelector('[data-route="study"],[data-xp-route="study"]');if(study)study.click();window.setTimeout(function(){if(window.CNC_TRAINING_PRACTICE){var state=window.CNC_TRAINING_PRACTICE.getState();if(state.wrong&&state.wrong.length)window.CNC_TRAINING_PRACTICE.renderQuestion(state.wrong[0],'wrong');}},140);}},true);window.addEventListener('hashchange',function(){window.setTimeout(render,80);});window.addEventListener('storage',render);}
function boot(){ensureAssets();bind();render();window.setTimeout(render,900);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
window.CNC_TRAINING_PROFILE={build:BUILD,snapshot:snapshot,render:render,runCheck:function(){var panel=document.getElementById('xp-training-profile'),data=snapshot();return{passed:Boolean(panel&&document.querySelector('link[data-cnc-training-profile]')&&data.lessons.length===12),build:BUILD,lessons:data.lessons.length,completed:data.completed,wrong:data.wrong,next:data.next,polling:false,observer:false};}};
})();
